## -*- encoding: utf-8 -*-
## This file (flashcards.sagetex.sage) was *autogenerated* from flashcards.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('flashcards', version='2015/08/26 v3.0-92d9f7a', version_check=True)
jobname="flashcards"
import hashlib
set_random_seed(int(hashlib.sha256(jobname.encode('utf-8')).hexdigest(), 16))
_st_.endofdoc()
