## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file sqrtReview2.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (sqrtReview2.sagetex.sage) was *autogenerated* from sqrtReview2.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('sqrtReview2', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()

