## -*- encoding: utf-8 -*-
## This file (./digInBasicRulesOfDifferentiation-figure2.sagetex.sage) was *autogenerated* from ./digInBasicRulesOfDifferentiation-figure2.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./digInBasicRulesOfDifferentiation-figure2', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
